stages:
  - test
  - build

test:
  image: python:3.10
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

build:
  image: docker:24
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t greeting-app .