name: Python CI

on: [push, pull_request]   # déclenché à chaque push ou PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: pip install pytest
    - run: pytest
